- README.md
Hellooooooooo, Quera! 😀
Please Accept my pull request :))
> Add Ali Safinal to README.md

- README.md
hey Quera!  please accept me too.
> Add Mohammad Shafei

- README.md
I added a brief introduction to Quera College, and added some links.
> Add brief Quera College intro

- README.md
add smasoudhosseini to README.md
> add smasoudhosseini

- README.md
Thanks for your awesome course Quera
> GoodBye Git

- README.md
> fixing my link

- README.md
Amirmohammad Kazemi Linkedin profile added.
Pull request for the last exercise of git-ninjas.
> Amirmohammad Kazemi

- README.md
> Mohammadali davarzani

- README.md
> Add My name and social URL

- README.md
> mahdi_hasan

- README.md
We had a good journey together (>‿◠)✌
> goodbye ninjas !

- README.md
> mohammad mansouri added

- README.md
> mj_taheri added!

- README.md
Reverts QueraTeam/git-ninjas#120
> Revert "add Amin Seifi"

- README.md
My name has recently added to git course participants .
> nafiseh sadeghi added

- README.md
> Iman Hamidi

- README.md
My name is MohammadHosein Masoon. I added my name at the end of the list.
> Added myself.

- README.md
adding myself to participants list.
> Danial_Azimi

- README.md
I am glad to contribute in your awesome git course. That was amazing!
> Adding my information

- README.md
"Ashkan Heidary Fazel" Just finished the course and added to the list
> Ashkan HeidaryFazel Added

- README.md
add my name into README.md and say goodbye to this great Git course!
> add myself :D

- README.md
> add mySelf

- README.md
> I was also added to the list

- README.md
> M.H.Ahmdi added to README.md

- README.md
> add AmirManshadi to README.md

- README.md
I've added the link to my Twitter account. The final assignment of the git course.
> Mehdi Jahani added his credentials.

- README.md
add my self in to end of the list :)
> add my self

- README.md
add kian kamgar to repository list
> add my name to repository
